// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXkEEJafcwv533mnPDug72FWYrep3u36Y',
    appId: '1:881788650274:web:97b9c3e36096b51847db7b',
    messagingSenderId: '881788650274',
    projectId: 'janaushadi-179e6',
    authDomain: 'janaushadi-179e6.firebaseapp.com',
    storageBucket: 'janaushadi-179e6.firebasestorage.app',
    measurementId: 'G-W4KJ4G9TQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfTmOv2rAyUktLVGoU-HUhFCVKyTYSE1w',
    appId: '1:881788650274:android:b6d88d72ee3fbc5647db7b',
    messagingSenderId: '881788650274',
    projectId: 'janaushadi-179e6',
    storageBucket: 'janaushadi-179e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm3nYGGxNxBTjHOSOJCCBGU4rJNJTrTA8',
    appId: '1:881788650274:ios:b8ba389080c48bd047db7b',
    messagingSenderId: '881788650274',
    projectId: 'janaushadi-179e6',
    storageBucket: 'janaushadi-179e6.firebasestorage.app',
    iosBundleId: 'com.example.bleAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm3nYGGxNxBTjHOSOJCCBGU4rJNJTrTA8',
    appId: '1:881788650274:ios:b8ba389080c48bd047db7b',
    messagingSenderId: '881788650274',
    projectId: 'janaushadi-179e6',
    storageBucket: 'janaushadi-179e6.firebasestorage.app',
    iosBundleId: 'com.example.bleAttendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXkEEJafcwv533mnPDug72FWYrep3u36Y',
    appId: '1:881788650274:web:12076249564ba34647db7b',
    messagingSenderId: '881788650274',
    projectId: 'janaushadi-179e6',
    authDomain: 'janaushadi-179e6.firebaseapp.com',
    storageBucket: 'janaushadi-179e6.firebasestorage.app',
    measurementId: 'G-SRPBBB3JCW',
  );
}
